#pragma config(Sensor, in1,    RIGHT_LINE_TRACKER, sensorLineFollower)
#pragma config(Sensor, in2,    RIGHT_POTENTIOMETER, sensorPotentiometer)
#pragma config(Sensor, in3,    GYRO_SENSOR,     sensorGyro)
#pragma config(Sensor, in5,    SECOND_BATTERY,  sensorAnalog)
#pragma config(Sensor, in6,    FRONT_LINE_TRACKER, sensorLineFollower)
#pragma config(Sensor, in7,    LEFT_POTENTIOMETER, sensorPotentiometer)
#pragma config(Sensor, in8,    LEFT_LINE_TRACKER, sensorLineFollower)
#pragma config(Sensor, dgtl1,  RIGHT_SHAFT_ENCODER, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEFT_SHAFT_ENCODER, sensorQuadEncoder)
#pragma config(Motor,  port1,           RIGHT_DRIVE1,   tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port3,           RIGHT_DRIVE2_AND_3, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           RIGHT_MOBILE_LIFT, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_CHAIN_BAR, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LEFT_CHAIN_BAR,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           CLAW,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LEFT_MOBILE_LIFT, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LEFT_DRIVE2_AND_3, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          LEFT_DRIVE1,    tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "Robot2_Functions.h"

string mainBattery,secoBattery,backBattery;
string Auton_Side = "Blue";
string Auton_Select = "Blue 22pt";
string Driver_Select = "Team";
string mode = "MainMenu1";
float Battery_Factor = 286.5;

void pre_auton()//*****************************************************************************************************************
{
  SensorValue[RIGHT_SHAFT_ENCODER] = 0;
  SensorValue[LEFT_SHAFT_ENCODER] = 0;

  bStopTasksBetweenModes = true;
  bLCDBacklight = true;
  clearLCDLine(0);
  clearLCDLine(1);
  const short leftButton = 1;
  const short centerButton = 2;
  const short rightButton = 4;
  while(bIfiRobotDisabled == true)
  {
    if (mode == "MainMenu1")//main menu----------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0,"Batt  Auto    > ");
      if (nLCDButtons == leftButton)
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "Battery"; //Battery Mode
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "Auton"; //Autonomous selection mode
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton)
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu2"; //Driver selection mode
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "Battery") //battery display mode:::::::::::::::::::::::::::::::
    {
      displayLCDString(0,0, "Pr:");
      sprintf(mainBattery, "%1.2f", nImmediateBatteryLevel/1000.0); //Build the value to be displayed
      displayNextLCDString(mainBattery);

      displayNextLCDString("  Se:");
      sprintf(secoBattery, "%1.2f", SensorValue[SECOND_BATTERY]/Battery_Factor);
      displayNextLCDString(secoBattery);

      displayLCDString(1,0, "Ba:");
      sprintf(backBattery, "%1.2f     Back", BackupBatteryLevel/1000.0);	//Build the value to be displayed
      displayNextLCDString(backBattery);

      if (nLCDButtons == rightButton) //Back to main menu
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu1";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "Auton") //autonomous selection mode:::::::::::::::::::::::::::::::::::
    {
      displayLCDString(0,0, "Auton: ");
      displayNextLCDString(Auton_Select);
      displayLCDString(1,0, "Back  Blue   Red");
      if (nLCDButtons == leftButton)
      {
        waitUntil(nLCDButtons != leftButton); //Back to main menu
        mode = "MainMenu1";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton) //Blue side autonomous
      {
      	waitUntil(nLCDButtons != centerButton);
      	Auton_Side = "Blue";
        mode = "Auton Path";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton) //Red side autonomous
      {
      	waitUntil(nLCDButtons != rightButton);
      	Auton_Side = "Red ";
        mode = "Auton Path";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "Auton Path") //Choosing Path
    {
    	displayLCDString(0,0, Auton_Side);
    	displayNextLCDString(": ");
    	displayNextLCDString(Auton_Select);
    	displayLCDString(1,0,"Back  22pt    > ");
    	if (nLCDButtons == leftButton)
      {
        waitUntil(nLCDButtons != leftButton); //Back to Auton page
        mode = "Auton";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton) //20 point
      {
      	waitUntil(nLCDButtons != centerButton);
      	if (Auton_Side == "Blue")//Blue
      	{
        	Auton_Select = "Blue 22pt";
        }
        else										//Red
        {
        	Auton_Select = "Red 22pt ";
        }
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton) //Next page of blue auton
      {
      	waitUntil(nLCDButtons != rightButton);
        mode = "Auton Path2";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }
    else if (mode == "Auton Path2") //Second slide of auton path selection
    {
    	displayLCDString(0,0, Auton_Side);
    	displayNextLCDString(": ");
    	displayNextLCDString(Auton_Select);
    	displayLCDString(1,0," <    12pt Block");
    	if (nLCDButtons == leftButton)
      {
        waitUntil(nLCDButtons != leftButton); //Back to main auton path page
        mode = "Auton Path";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton) //10 point
      {
      	waitUntil(nLCDButtons != centerButton);
      	if (Auton_Side == "Blue")//Blue
      	{
        	Auton_Select = "Blue 12pt";
        }
        else										//Red
        {
        	Auton_Select = "Red 12pt ";
        }
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton) //Block opponent auton
      {
      	waitUntil(nLCDButtons != rightButton);
        if (Auton_Side == "Blue")//Blue
      	{
        	Auton_Select = "Blue Block";
        }
        else										//Red
        {
        	Auton_Select = "Red Block ";
        }
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }




    else if (mode == "MainMenu2")//2nd slide of main menu-----------------------------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0," <   Driver   > ");
      if (nLCDButtons == leftButton)//Back to Main menu 1
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu1";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "Driver"; //Driver selection mode
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton)
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu3"; //Going to 3rd Main Menu slide
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }
    else if (mode == "Driver") //driver selection mode
    {
      displayLCDString(0,0, "Driv Select:");
      displayNextLCDString(Driver_Select);
      displayLCDString(1,0,"Back  Skil  Team");
      if (nLCDButtons == leftButton)
      {
        waitUntil(nLCDButtons != leftButton); //Back to main menu1
        mode = "MainMenu2";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton) //Driver Skills mode
      {
        Driver_Select = "Skil";
        clearLCDLine(0);
      }
      else if (nLCDButtons == rightButton) //Teamwork mode
      {
        Driver_Select = "Team";
        clearLCDLine(0);
      }
    }


    else if (mode == "MainMenu3")//3rd slide of main menu-----------------------------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0," <    Line    > ");
      if (nLCDButtons == leftButton)//Back to Main menu 2
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu2";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)//Line Tracker Values Display Mode
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "Line";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton)//Going to Main Menu 4
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu4";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "Line") //Display Line Tracker Values
    {
      string right_val,left_val,front_val;
      bool front = false;
      while(nLCDButtons != leftButton)
      {
        if (nLCDButtons == centerButton)
        {
          waitUntil(nLCDButtons != centerButton);
          if (front == true)
          {
            front = false;
          }
          else
          {
            front = true;
          }
        }
        if (front == false) //Back Sensors
        {
          clearLCDLine(0);
          right_val = SensorValue[RIGHT_LINE_TRACKER];
          displayLCDString(0,0,"Right Val:");
          displayNextLCDString(right_val);

          clearLCDLine(1);
          left_val = SensorValue[LEFT_LINE_TRACKER];
          displayLCDString(1,0,"Left Val:");
          displayNextLCDString(left_val);
        }
        else //Front Sensor
        {
          clearLCDLine(0);
          clearLCDLine(1);
          front_val = SensorValue[FRONT_LINE_TRACKER];
          displayLCDString(0,0,"Front Value:");
          displayNextLCDString(front_val);
        }
        wait1Msec(500);
      }
      if (nLCDButtons == leftButton)//Returning to 3rd slide of Main menu
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu3";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }


    else if (mode == "MainMenu4")//4th slide of main menu-----------------------------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0," <  OpticSen  > ");
      if (nLCDButtons == leftButton)//Back to Main menu 3
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu3";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)//Display Optical Sensor Values mode
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "OpticSen";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton)//Going to 5th Main Menu slide
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu5";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "OpticSen") //Display Optical Sensor Values mode
    {
      string Right_val,Left_val;
      SensorValue[RIGHT_SHAFT_ENCODER] = 0;
      SensorValue[LEFT_SHAFT_ENCODER] = 0;
      while (nLCDButtons != leftButton)
      {
        clearLCDLine(0);
        Right_val = SensorValue[RIGHT_SHAFT_ENCODER];
        displayLCDString(0,0,"Right Val:");
        displayNextLCDString(Right_val);

        clearLCDLine(1);
        Left_val = -SensorValue[LEFT_SHAFT_ENCODER];
        displayLCDString(1,0,"Left Val:");
        displayNextLCDString(Left_val);

        wait1Msec(500);
        if (nLCDButtons == centerButton)
        {
          SensorValue[RIGHT_SHAFT_ENCODER] = 0;
          SensorValue[LEFT_SHAFT_ENCODER] = 0;
        }
        wait1Msec(500);
      }
      if (nLCDButtons == leftButton)//Returning to 4th slide of Main Menu
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu4";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }


    else if (mode == "MainMenu5")//5th slide of main menu-----------------------------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0," <  Potmeter  > ");
      if (nLCDButtons == leftButton)//Back to Main menu 4
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu4";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)//Display Potentiometer Values mode
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "Potmeter";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == rightButton)//Display Potentiometer Values mode
      {
        waitUntil(nLCDButtons != rightButton);
        mode = "MainMenu6";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "Potmeter") //Display Optical Sensor Values mode
    {
      string Right_val,Left_val;
      while (nLCDButtons != leftButton)
      {
        clearLCDLine(0);
        Right_val = SensorValue[RIGHT_POTENTIOMETER];
        displayLCDString(0,0,"Right Val:");
        displayNextLCDString(Right_val);

        clearLCDLine(1);
        Left_val = SensorValue[LEFT_POTENTIOMETER];
        displayLCDString(1,0,"Left Val:");
        displayNextLCDString(Left_val);

        wait1Msec(500);
      }
      if (nLCDButtons == leftButton)//Returning to 5th slide of Main Menu
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu5";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "MainMenu6")//6th slide of main menu-----------------------------------------------------------------------------------
    {
      displayLCDCenteredString(0,"Main Menu");
      displayLCDString(1,0," <  GyroSens");
      if (nLCDButtons == leftButton)//Back to Main menu 5
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu5";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)//Display Gyro Sensor Values mode
      {
        waitUntil(nLCDButtons != centerButton);
        mode = "GyroSens";
        clearLCDLine(0);
        clearLCDLine(1);
      }
    }

    else if (mode == "GyroSens") //Display Gyro Sensor Values mode
    {
      string Gyro_val;
      clearLCDLine(0);
      clearLCDLine(1);

      Gyro_val = SensorValue[GYRO_SENSOR];
      displayLCDString(0,0,"Gyro Val:");
      displayNextLCDString(Gyro_val);

      displayLCDString(1,0,"Back  Reset");
      wait1Msec(300);
      if (nLCDButtons == leftButton)//Returning to 6th slide of Main Menu
      {
        waitUntil(nLCDButtons != leftButton);
        mode = "MainMenu6";
        clearLCDLine(0);
        clearLCDLine(1);
      }
      else if (nLCDButtons == centerButton)//Resetting gyro sensor
      {
        waitUntil(nLCDButtons != centerButton);
        SensorType[in3] = sensorNone;
				wait1Msec(1000);
				//Reconfigure Analog Port 3 as a Gyro sensor and allow time for ROBOTC to calibrate it
				SensorType[in3] = sensorGyro;
				wait1Msec(2000);
      }
    }



  }
  clearLCDLine(0);
  clearLCDLine(1);

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



//Autonomous****************************************************************************************************************************
const int RightMobileMin = 750;//785
const int LeftMobileMin = 770;

const int RightMobileMax = 2270;//2420
const int LeftMobileMax = 2270;

const int MobileStage1 = 1670;
const int MobileStage2 = 1750;
const int MobileStage3 = 2000;

const int BackLineVal = 3050;//3046
const int FrontLineVal = 3020;//3005,3025
const int PipeColorVal = 2650;

task autonomous()
{
  //Default Autonomous(Blue side 22pt) ####################################################################################
  if (Auton_Select == "Blue 22pt")
  {
    //Going towards mobile goal------------------------------------------------------------
    motor[CLAW] = -20;
    RightMove(-45);
    LeftMove(-45);
    ChainBar(-95);
    wait1Msec(500);
    ChainBar(0);
    RightMove(-43);
    LeftMove(-43);
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
   	motor[RIGHT_MOBILE_LIFT] = -5;
   	motor[LEFT_MOBILE_LIFT] = -8;
    Move(700,-85,700,-85);
    SetMogoLiftPower(-5);
    wait1Msec(300);
    //Picking up Mobile Goal
		ChainBar(65);
    MobileLift(MobileStage1 - 200,MobileStage1 - 200,55);
    //Putting cone on Mobile Goal
    wait1Msec(600);
    ChainBar(0);
    motor[CLAW] = 90;
    wait1Msec(250);
    ChainBar(-110);
    wait1Msec(430);
    ChainBar(0);
    motor[CLAW] = 0;
    //Bringing Mobile Goal in
    MobileLift(RightMobileMax -100,LeftMobileMax -100,60);
    wait1Msec(200);
    //Moving towards pipe
   	Move(210,60,210,60);
    Move(510,100,300,65);
    StopAtLine(BackLineVal,20,20,8);
    Move(200,90,200,90);
    Move(390,100,250,65);
    Move(7,80,7,80);
    wait1Msec(300);
    GyroTurn(-1040,60,"left");
    wait1Msec(300);
    //Scoring Mobile Goal
    SetMovePower(-30);
    MobileLift(MobileStage2 + 145,MobileStage2 + 145,-55);
    SetMovePower(-70);
    wait1Msec(1100);
    SetMovePower(0);
    SensorValue[GYRO_SENSOR] = 0;
    MobileLift(MobileStage3,MobileStage3,50);
    //Pulling out
    StopAtLine(FrontLineVal,40,40,6);
    Move(45,40,45,40);
    wait1Msec(300);

    //Getting Mobile Goal on the right of stationary goal-------------------------------------------------------------------------------------
  	Move(367,-80,60,23);
    wait1Msec(250);
   	SetMogoLiftPower(-80);
    Move(540,-80,0,0);
    SetMogoLiftPower(0);
    wait1Msec(150);
    MobileLift(RightMobileMin+10,LeftMobileMin+10,-127);
    SetMogoLiftPower(-5);
    wait1Msec(100);
    Move(360,-90,350,-90);
    wait1Msec(300);
    MobileLift(RightMobileMax - 100,LeftMobileMax - 100,60);
    wait1Msec(100);
    //Heading back towards pipes
    PIDGyroTurn(-50,true,false);
    wait1Msec(100);
    Move(30,-40,30,-40);
    Move(70,-90,70,-90);
    //Scoring 2nd Mobile Goal
    StopAtLine(BackLineVal,-45,-45,1);
    SetMogoLiftPower(-50);
    LineAlign(PipeColorVal,-40);
    SetMogoLiftPower(0);
    wait1Msec(300);
    //Getting out of the zone
    SetMogoLiftPower(50);
    SetMovePower(50);
    wait1Msec(700);
    SetMogoLiftPower(0);
    //Moving out of the zone
    LineAlign(BackLineVal,20);
    wait1Msec(300);

    //Going for 3rd mobile goal-----------------------------------------------------------------------------------------------------------------
    SetMogoLiftPower(-50);
    PIDGyroTurn(1970,false,true,"both",5);
    wait1Msec(200);
    SensorValue[GYRO_SENSOR] = 0;
    MobileLift(RightMobileMin+10,LeftMobileMin+10,-127);
    SetMogoLiftPower(-5);
    Move(30,-20,30,-20);
    Move(25,-50,25,-50);
    StopAtLine(FrontLineVal,-70,-70,6);
    Move(350,-100,350,-100);
    wait1Msec(250);
    MobileLift(RightMobileMax - 20,LeftMobileMax - 20,50);
    while (SensorValue[GYRO_SENSOR] > 50 || SensorValue[GYRO_SENSOR] < -20)
    {
    	int sign = SensorValue[GYRO_SENSOR]/abs(SensorValue[GYRO_SENSOR]);
    	LeftMove(25*sign);
    }
    LeftMove(0);
    //Heading to red pipes
    Move(30,-40,30,-40);
    Move(340,-70,340,-70);
    wait1Msec(300);
    Move(335,-90,0,0);//340
    LineAlign(3000,-40);
    //Scoring 3rd Mobile Goal
    SetMovePower(-65);
    MobileLift(MobileStage2 + 105,MobileStage2 + 105,-60);
    wait1Msec(500);
    SetMovePower(0);
    SensorValue[GYRO_SENSOR] = 0;
    MobileLift(MobileStage3,MobileStage3,127);
    //Moving out of pipes
    StopAtLine(FrontLineVal,40,40,6);
    Move(30,40,30,40);
    wait1Msec(300);

    //Getting 4th Mobile Goal on the right of stationary goal-------------------------------------------------------------------------------------
  	Move(367,-80,50,23);
    wait1Msec(250);
    SetMogoLiftPower(-60);
    Move(560,-80,0,0);
    wait1Msec(150);
    MobileLift(RightMobileMin+10,LeftMobileMin+10,-127);
    SetMogoLiftPower(-5);
    wait1Msec(100);
    Move(360,-90,360,-90);
    wait1Msec(300);
    MobileLift(RightMobileMax - 100,LeftMobileMax - 100,60);
    wait1Msec(50);
   	//heading back to red pipes
    PIDGyroTurn(0,true,false);
    wait1Msec(100);
    Move(25,-40,25,-40);
    Move(25,-90,25,-90);
    //scoring 4th mogo
    StopAtLine(BackLineVal,-45,-45,1);
    SetMogoLiftPower(-60);
    LineAlign(PipeColorVal,-40);
    SetMogoLiftPower(0);
    wait1Msec(300);
    //Getting out of the zone
    SetMogoLiftPower(50);
    SetMovePower(35);
    wait1Msec(600);
    MobileLift(RightMobileMax - 50,LeftMobileMax - 50,120);
    StopAtLine(BackLineVal,30,30,1);
    wait1Msec(300);

    //Going for 5th mobile goal-----------------------------------------------------------------------------------------------------------------
    SetMogoLiftPower(-40);
    PIDGyroTurn(1925,false,true);
    SetMogoLiftPower(-50);
    wait1Msec(200);
    SensorValue[GYRO_SENSOR] = 0;
    MobileLift(RightMobileMin+5,LeftMobileMin+10,-127);
    SetMogoLiftPower(-8);
    Move(50,-50,50,-50);
    StopAtLine(FrontLineVal,-70,-70,6);
    Move(350,-100,350,-100);
    wait1Msec(300);
    MobileLift(RightMobileMax - 20,LeftMobileMax - 20,50);
    while (SensorValue[GYRO_SENSOR] > 90 || SensorValue[GYRO_SENSOR] < -50)
    {
    	int sign = SensorValue[GYRO_SENSOR]/abs(SensorValue[GYRO_SENSOR]);
    	LeftMove(25*sign);
    }
    LeftMove(0);
    wait1Msec(100);
    //Heading to blue pipes
    StopAtLine(BackLineVal,-88,-88,8);
    motor[RIGHT_MOBILE_LIFT] = -55;
    motor[LEFT_MOBILE_LIFT] = -55;
    LineAlign(PipeColorVal,-40);
    motor[RIGHT_MOBILE_LIFT] = 0;
    motor[LEFT_MOBILE_LIFT] = 0;
    //Scoring 5th Mobile Goal
    wait1Msec(200);
    //Getting out of the zone
    motor[RIGHT_MOBILE_LIFT] = 50;
    motor[LEFT_MOBILE_LIFT] = 50;
    StopAtLine(FrontLineVal,40,40,6);
    motor[RIGHT_MOBILE_LIFT] = 0;
    motor[LEFT_MOBILE_LIFT] = 0;

    //Going for 6th mobile goal------------------------------------------------------
    wait1Msec(300);
    SetMogoLiftPower(-70);
    PIGyroTurn(-1065,50,2,false);
    motor[RIGHT_MOBILE_LIFT] = -5;
    motor[LEFT_MOBILE_LIFT] = -8;
    wait1Msec(200);
    RightMove(-115);
    LeftMove(-80);
    wait1Msec(1700);
    SetMovePower(0);
    wait1Msec(200);
    MobileLift(MobileStage3+30,MobileStage3+30,50);
    wait1Msec(200);
    //Heading back to blue pipes
    Move(900,80,1200,100);
    wait1Msec(150);
    Move(0,0,1000,90);
    wait1Msec(200);
    SetMogoLiftPower(-80);
    Move(100,-90,100,-90);
    wait1Msec(150);
    SetMogoLiftPower(0);
    wait1Msec(150);
    SetMogoLiftPower(20);
    Move(50,90,50,90);
  }

  //Red Side 22pt Autonomous#############################################################################################
  else if(Auton_Select == "Red 22pt ")
  {
    //Going towards mobile goal
    motor[CLAW] = -20;
    RightMove(-45);
    LeftMove(-45);
    ChainBar(-95);
    wait1Msec(500);
    ChainBar(0);
    RightMove(-43);
    LeftMove(-43);
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
   	motor[RIGHT_MOBILE_LIFT] = -5;
   	motor[LEFT_MOBILE_LIFT] = -8;
    Move(700,-85,700,-85);
    SetMogoLiftPower(-5);
    wait1Msec(300);
    //Picking up Mobile Goal
		ChainBar(65);
    MobileLift(MobileStage1 - 200,MobileStage1 - 200,55);
    //Putting cone on Mobile Goal
    wait1Msec(600);
    ChainBar(0);
    motor[CLAW] = 90;
    wait1Msec(250);
    ChainBar(-110);
    wait1Msec(430);
    ChainBar(0);
    motor[CLAW] = 0;
    //Bringing Mobile Goal in
    MobileLift(RightMobileMax -100,LeftMobileMax -100,60);
    wait1Msec(200);
    //Moving towards pipe
    Move(500,50,570,65);
    LineAlign(BackLineVal,20);
    Move(300,37,600,90);
    Move(75,60,90,90);
    wait1Msec(400);
    Move(0,0,630,60);
    wait1Msec(400);
    //Scoring Mobile Goal
   SetMovePower(-30);
    MobileLift(MobileStage2 + 145,MobileStage2 + 145,-55);
    SetMovePower(-70);
    wait1Msec(1100);
    SetMovePower(0);
    MobileLift(MobileStage3,MobileStage3,50);
    //Pulling out
    StopAtLine(FrontLineVal,40,40,6);
    wait1Msec(300);
  }

  else if(Auton_Select == "Blue 12pt")//Blue Side 12pt Autonomous#############################################################################################
  {
		motor[CLAW] = -20;
    RightMove(-45);
    LeftMove(-45);
    ChainBar(-95);
    wait1Msec(500);
    ChainBar(0);
    RightMove(-43);
    LeftMove(-43);
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
   	motor[RIGHT_MOBILE_LIFT] = -5;
   	motor[LEFT_MOBILE_LIFT] = -8;
    Move(700,-85,700,-85);
    SetMogoLiftPower(-5);
    wait1Msec(300);
    //Picking up Mobile Goal
		ChainBar(65);
    MobileLift(MobileStage1 - 200,MobileStage1 - 200,55);
    //Putting cone on Mobile Goal
    wait1Msec(600);
    ChainBar(0);
    motor[CLAW] = 90;
    wait1Msec(250);
    ChainBar(-110);
    wait1Msec(430);
    ChainBar(0);
    motor[CLAW] = 0;
    //Bringing Mobile Goal in
    MobileLift(RightMobileMax -100,LeftMobileMax -100,60);
    wait1Msec(200);
    //Moving towards pipe
    Move(570,65,470,50);
    LineAlign(BackLineVal,20);
    Move(350,90,150,37);
    wait1Msec(400);
    Move(590,60,0,0);
    wait1Msec(400);
    LineAlign(3000,-30);
    //Scoring Mobile Goal
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
    wait1Msec(300);
    //Moving out of the zone
    SetMovePower(35);
    wait1Msec(600);
    MobileLift(RightMobileMax - 50,LeftMobileMax - 50,120);
    LineAlign(BackLineVal,20);
  }

  else if(Auton_Select == "Red 12pt ")//Red Side 12pt Autonomous#############################################################################################
  {
  	//Going towards mobile goal
    motor[CLAW] = -20;
    RightMove(-45);
    LeftMove(-45);
    ChainBar(-95);
    wait1Msec(500);
    ChainBar(0);
    RightMove(-43);
    LeftMove(-43);
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
   	motor[RIGHT_MOBILE_LIFT] = -5;
   	motor[LEFT_MOBILE_LIFT] = -8;
    Move(700,-85,700,-85);
    SetMogoLiftPower(-5);
    wait1Msec(300);
    //Picking up Mobile Goal
		ChainBar(65);
    MobileLift(MobileStage1 - 200,MobileStage1 - 200,55);
    //Putting cone on Mobile Goal
    wait1Msec(600);
    ChainBar(0);
    motor[CLAW] = 90;
    wait1Msec(250);
    ChainBar(-110);
    wait1Msec(430);
    ChainBar(0);
    motor[CLAW] = 0;
    //Bringing Mobile Goal in
    MobileLift(RightMobileMax -100,LeftMobileMax -100,60);
    wait1Msec(200);
    //Moving towards pipe
    Move(470,50,570,65);
    LineAlign(BackLineVal,20);
    Move(150,37,350,90);
    wait1Msec(400);
    Move(0,0,610,60);
    wait1Msec(400);
    LineAlign(3000,-30);
    //Scoring Mobile Goal
    MobileLift(RightMobileMin + 10,LeftMobileMin + 10,-127);
    wait1Msec(300);
    //Moving out of the zone
    SetMovePower(35);
    wait1Msec(600);
    MobileLift(RightMobileMax - 50,LeftMobileMax - 50,120);
    LineAlign(BackLineVal,20);
  }

  else if (Auton_Select == "Blue Block" || Auton_Select == "Red Block ")
  {
  	SetMovePower(120);
  	wait1Msec(1200);
  	SetMovePower(60);
  	wait1Msec(1000);
  	SetMovePower(0);
  }
}
//Driver Control-------------------------------------------------------------------------------------------
task usercontrol()
{
  float fast,slow;
  if (Driver_Select == "Team") //Teamwork Speed
  {
    fast = 1.75;
    slow = 2.2;
  }
  else //Skills Speed
  {
    fast = 1.5;
    slow = 1.8;
  }
  float power_reduction = slow;
  int threshold = 10;
  bool Right_done = false, Left_done = false;
  while (true)
  {
    //Driving---------------------------------------------------
    //Changing Speeds
    if (vexRT[Btn6D])
    {
      waitUntil(vexRT[Btn6D] == 0);
      if (power_reduction == slow)
      {
        power_reduction = fast;
      }
      else
      {
        power_reduction = slow;
      }
    }

    //Tank Control
    if (vexRT[Ch2] > threshold || vexRT[Ch2] < -threshold)
    {
      RightMove(vexRT[Ch2]/power_reduction);
    }
    else
    {
      RightMove(0);
    }

    if (vexRT[Ch3] > threshold || vexRT[Ch3] < -threshold)
    {
      LeftMove(vexRT[Ch3]/power_reduction);
    }
    else
    {
      LeftMove(0);
    }

    //Mobile Goal Pickup-----------------------------------------------------
    //1-3 cones----------------------------------------------
    if (vexRT[Btn8L] == 1)
    {
    	Right_done = false;
      Left_done = false;
      if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage1 + 75)
      {
	      while (!vexRT[Btn8D] && !vexRT[Btn8U] && !vexRT[Btn8R] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
	      {
	        if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage1 + 210)
	        {
	          motor[RIGHT_MOBILE_LIFT] = -45;
	        }
	        else
	        {
	          motor[RIGHT_MOBILE_LIFT] = 0;
	          Right_done = true;
	        }
	        if (SensorValue[LEFT_POTENTIOMETER] > MobileStage1 + 210)
	        {
	          motor[LEFT_MOBILE_LIFT] = -45;
	        }
	        else
	        {
	          motor[LEFT_MOBILE_LIFT] = 0;
	          Left_done = true;
	        }
	      }
      }
      else if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage1 - 50)
      {
        while (!vexRT[Btn8D] && !vexRT[Btn8U] && !vexRT[Btn8R] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
        {
          if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage1 - 190)
          {
            motor[RIGHT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[RIGHT_MOBILE_LIFT] = 0;
            Right_done = true;
          }
          if (SensorValue[LEFT_POTENTIOMETER] < MobileStage1 - 190)
          {
            motor[LEFT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[LEFT_MOBILE_LIFT] = 0;
            Left_done = true;
          }
        }
      }
    }
    //4 cones-----------------------------
    if (vexRT[Btn8U])
    {
      Right_done = false;
      Left_done = false;
      if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage2 + 50)
      {
        while (!vexRT[Btn8D] && !vexRT[Btn8L] && !vexRT[Btn8R] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
	      {
	        if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage2 + 135)
	        {
	          motor[RIGHT_MOBILE_LIFT] = -50;
	        }
	        else
	        {
	          motor[RIGHT_MOBILE_LIFT] = 0;
	          Right_done = true;
	        }
	        if (SensorValue[LEFT_POTENTIOMETER] > MobileStage2 + 135)
	        {
	          motor[LEFT_MOBILE_LIFT] = -50;
	        }
	        else
	        {
	          motor[LEFT_MOBILE_LIFT] = 0;
	          Left_done = true;
	        }
	      }
	    }
      else if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage2)
      {
        while (!vexRT[Btn8D] && !vexRT[Btn8L] && !vexRT[Btn8R] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
        {
          if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage2 - 175)
          {
            motor[RIGHT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[RIGHT_MOBILE_LIFT] = 0;
            Right_done = true;
          }
          if (SensorValue[LEFT_POTENTIOMETER] < MobileStage2 - 175)
          {
            motor[LEFT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[LEFT_MOBILE_LIFT] = 0;
            Left_done = true;
          }
        }
      }
    }
    //5 cones
    if (vexRT[Btn8R])
    {
      Right_done = false;
      Left_done = false;
      if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage3 + 50)
      {
        while (!vexRT[Btn8D] && !vexRT[Btn8L] && !vexRT[Btn8U] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
        {
	        if (SensorValue[RIGHT_POTENTIOMETER] > MobileStage3 + 40)
	        {
	          motor[RIGHT_MOBILE_LIFT] = -50;
	        }
	        else
	        {
	          motor[RIGHT_MOBILE_LIFT] = 0;
	          Right_done = true;
	        }
	        if (SensorValue[LEFT_POTENTIOMETER] > MobileStage3 + 40)
	        {
	          motor[LEFT_MOBILE_LIFT] = -50;
	        }
	        else
	        {
	          motor[LEFT_MOBILE_LIFT] = 0;
	          Left_done = true;
	        }
	      }
	    }
      else if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage3 + 30)
      {
        while (!vexRT[Btn8D] && !vexRT[Btn8L] && !vexRT[Btn8U] && !vexRT[Btn6U]
        && (!Right_done || !Left_done))
        {
          if (SensorValue[RIGHT_POTENTIOMETER] < MobileStage3 - 270)
          {
            motor[RIGHT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[RIGHT_MOBILE_LIFT] = 0;
            Right_done = true;
          }
          if (SensorValue[LEFT_POTENTIOMETER] < MobileStage3 - 270)
          {
            motor[LEFT_MOBILE_LIFT] = 50;
          }
          else
          {
            motor[LEFT_MOBILE_LIFT] = 0;
            Left_done = true;
          }
        }
      }
    }

    //Raising or lowering Mobile Lift--------------------------------------

    if (vexRT[Btn8D] && SensorValue[RIGHT_POTENTIOMETER] < RightMobileMax)
    {
      motor[RIGHT_MOBILE_LIFT] = 80;
    }
    else if (vexRT[Btn6U] && SensorValue[RIGHT_POTENTIOMETER] > RightMobileMin+30)
    {
      motor[RIGHT_MOBILE_LIFT] = -70;
    }
    else
    {
      motor[RIGHT_MOBILE_LIFT] = 0;
    }

    if (vexRT[Btn8D] && SensorValue[LEFT_POTENTIOMETER] < LeftMobileMax)
    {
      motor[LEFT_MOBILE_LIFT] = 80;
    }
    else if (vexRT[Btn6U] && SensorValue[LEFT_POTENTIOMETER] > LeftMobileMin - 10)
    {
      motor[LEFT_MOBILE_LIFT] = -70;
    }
    else
    {
      motor[LEFT_MOBILE_LIFT] = 0;
    }



    //Chain Bar
    if(vexRT[Btn7U] == 1)//Extending Scissor Lift
    {
      ChainBar(127);
    }
    else if(vexRT[Btn7D] == 1)//Contracting Scissor Lift
    {
      ChainBar(-90);
    }
    else//Powering Scissor Lift Motors off
    {
      ChainBar(0);
    }

    //CLAW
    if(vexRT[Btn5U])//Opening CLAW
    {
      motor[CLAW] = 30;
    }
    else if(vexRT[Btn5D])//Closing CLAW
    {
      motor[CLAW] = -40;
    }
    else//Powering Off CLAW Motors
    {
      motor[CLAW] = 0;
    }
  }
}
